# Generated by Django 2.0.2 on 2018-04-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcash',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа (sum)'),
        ),
        migrations.AlterField(
            model_name='tcredits',
            name='suma',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма кредита (suma)'),
        ),
        migrations.AlterField(
            model_name='tcredits',
            name='vnoska',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Платеж (vnoska)'),
        ),
    ]
