# Generated by Django 2.0.2 on 2018-04-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0003_easypaypayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='easypaypayment',
            old_name='cancel_date',
            new_name='cancel_dt',
        ),
        migrations.RenameField(
            model_name='tcash',
            old_name='pb_code',
            new_name='service_code',
        ),
    ]
