# Generated by Django 2.0.2 on 2018-04-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0004_auto_20180406_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='City24Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(verbose_name='Номер EF в системе City24')),
                ('order_id', models.BigIntegerField(verbose_name='Уникальный идентификатор транзакции City24')),
                ('account', models.CharField(max_length=128, verbose_name='Идентификатор пользователя (№ договора)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cумма платежа')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтвержден?')),
                ('confirmed_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата заказа')),
                ('canceled', models.BooleanField(default=False, verbose_name='Отменен?')),
                ('cancel_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены заказа')),
            ],
            options={
                'verbose_name_plural': 'Транзакции City24',
                'verbose_name': 'Транзакция City24',
            },
        ),
    ]
