# Generated by Django 2.0.2 on 2018-03-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180326_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='two_authy',
            field=models.BooleanField(default=False, verbose_name='Двухфакторная аутентификация'),
        ),
    ]
