# Generated by Django 2.0.2 on 2018-02-28 15:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.CharField(max_length=64, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('schedule', ckeditor.fields.RichTextField(verbose_name='График')),
                ('title_text', ckeditor.fields.RichTextField(verbose_name='Текст снизу')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
