# Generated by Django 2.0.2 on 2018-02-28 15:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='footer_text',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Текст снизу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='title_text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст вверху'),
        ),
    ]
