# Generated by Django 2.0.2 on 2018-02-28 16:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_auto_20180228_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=ckeditor.fields.RichTextField(verbose_name='Адрес'),
        ),
    ]
