# Generated by Django 2.0.2 on 2018-02-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20180228_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name_plural': 'Номера телефонов',
                'verbose_name': 'Номер телефона',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='phones',
            field=models.ManyToManyField(to='communication.PhoneNumber', verbose_name='Телефоны'),
        ),
    ]
