# Generated by Django 2.0.2 on 2018-02-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_auto_20180228_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clients_photos', verbose_name='Фото клиента')),
                ('name', models.CharField(max_length=128, verbose_name='Имя клиента')),
                ('status', models.CharField(max_length=64, verbose_name='Статус клиента')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
