# Generated by Django 2.0.2 on 2018-02-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_agreement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
    ]
