# Generated by Django 2.0.2 on 2018-02-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_auto_20180228_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Электронная почта',
                'verbose_name_plural': 'Электронные почты',
            },
        ),
        migrations.AlterField(
            model_name='agreement',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='communication.Email', verbose_name='Электронная почта'),
        ),
    ]
