# Generated by Django 2.0.2 on 2018-03-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_auto_20180228_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='active',
            field=models.BooleanField(default=False, help_text='Будет использоваться только первая из активных почт', verbose_name='Активная Почта, используемая при отправке писем "напишите нам"'),
        ),
    ]
