# Generated by Django 2.0.2 on 2018-03-05 21:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_socialnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст статьи')),
                ('image', models.ImageField(upload_to='blog_items', verbose_name='Картинка')),
                ('date', models.DateField(verbose_name='Дата анонса')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи в блоге',
            },
        ),
    ]
