# Generated by Django 2.0.2 on 2018-03-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_lastarticles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnet',
            name='image',
        ),
    ]
