# Generated by Django 2.0.2 on 2018-03-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0013_remove_socialnet_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('icon', models.CharField(choices=[('general', 'Общие вопросы'), ('execution', 'Оформление заявки'), ('card', 'Банковская карта'), ('credit', 'Кредитный договор'), ('personal', 'Личный кабинет'), ('credit_manipulation', 'Как погасить / увеличить кредит')], max_length=64, verbose_name='Иконка')),
            ],
            options={
                'verbose_name_plural': 'FAQ категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вопроса')),
                ('link', models.CharField(help_text='Используйте ссылку вида /#html_id для блока лэндинга. Остальные ссылки указывать полностью (https://...)', max_length=255, verbose_name='URL-адрес')),
            ],
            options={
                'verbose_name': 'FAQ вопросы',
            },
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='faq_items',
            field=models.ManyToManyField(to='communication.FaqItem'),
        ),
    ]
