# Generated by Django 2.0.2 on 2018-03-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0015_auto_20180308_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotLinePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='Номер телефона')),
                ('schedule_start', models.TimeField(verbose_name='Время активности, начиная с:')),
                ('schedule_end', models.TimeField(verbose_name='Время активности, заканчивая в:')),
            ],
            options={
                'verbose_name': 'Горячая линия',
                'verbose_name_plural': 'Горячая линия',
            },
        ),
        migrations.CreateModel(
            name='WriteUsEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Почта',
                'verbose_name_plural': 'Почта для "Напишите нам"',
            },
        ),
        migrations.RemoveField(
            model_name='email',
            name='active',
        ),
        migrations.AddField(
            model_name='writeusemail',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='communication.Email', verbose_name='Электронная почта'),
        ),
    ]
