# Generated by Django 2.0.2 on 2018-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0016_auto_20180308_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotlinephone',
            name='schedule_end',
            field=models.TimeField(null=True, verbose_name='Время активности, заканчивая в:'),
        ),
        migrations.AlterField(
            model_name='hotlinephone',
            name='schedule_start',
            field=models.TimeField(null=True, verbose_name='Время активности, начиная с:'),
        ),
    ]
