# Generated by Django 2.0.2 on 2018-03-12 17:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0017_auto_20180311_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='meta_description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Meta description страницы'),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Meta title страницы'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Title страницы'),
        ),
    ]
