# Generated by Django 2.0.2 on 2018-03-12 17:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0018_auto_20180312_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title страницы')),
                ('meta_title', models.CharField(max_length=255, null=True, verbose_name='Meta title страницы')),
                ('meta_description', ckeditor.fields.RichTextField(null=True, verbose_name='Meta description страницы')),
                ('faq_categories', models.ManyToManyField(to='communication.FaqCategory', verbose_name='Категории с вопросами')),
            ],
            options={
                'verbose_name_plural': 'FAQ страница',
                'verbose_name': 'Страница',
            },
        ),
    ]
