# Generated by Django 2.0.2 on 2018-03-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0019_faq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faq',
            new_name='FaqPageStatic',
        ),
    ]
