# Generated by Django 2.0.2 on 2018-03-12 18:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0022_auto_20180312_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='blogitem',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок'),
        ),
    ]
