# Generated by Django 2.0.2 on 2018-03-12 19:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0023_auto_20180312_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='text_ua',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_ua',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contact',
            name='footer_text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст снизу'),
        ),
        migrations.AddField(
            model_name='contact',
            name='footer_text_ua',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст снизу'),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Meta description страницы'),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_description_ua',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Meta description страницы'),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Meta title страницы'),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_title_ua',
            field=models.CharField(max_length=255, null=True, verbose_name='Meta title страницы'),
        ),
        migrations.AddField(
            model_name='contact',
            name='schedule_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='График'),
        ),
        migrations.AddField(
            model_name='contact',
            name='schedule_ua',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='График'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title страницы'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст вверху'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_text_ua',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст вверху'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_ua',
            field=models.CharField(max_length=255, null=True, verbose_name='Title страницы'),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='name_ua',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название вопроса'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='name_ua',
            field=models.CharField(max_length=255, null=True, verbose_name='Название вопроса'),
        ),
        migrations.AddField(
            model_name='faqpagestatic',
            name='meta_description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Meta description страницы'),
        ),
        migrations.AddField(
            model_name='faqpagestatic',
            name='meta_description_ua',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Meta description страницы'),
        ),
        migrations.AddField(
            model_name='faqpagestatic',
            name='meta_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Meta title страницы'),
        ),
        migrations.AddField(
            model_name='faqpagestatic',
            name='meta_title_ua',
            field=models.CharField(max_length=255, null=True, verbose_name='Meta title страницы'),
        ),
        migrations.AddField(
            model_name='faqpagestatic',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title страницы'),
        ),
        migrations.AddField(
            model_name='faqpagestatic',
            name='title_ua',
            field=models.CharField(max_length=255, null=True, verbose_name='Title страницы'),
        ),
    ]
