# Generated by Django 2.0.2 on 2018-03-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0024_auto_20180312_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название категории')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='Название категории')),
                ('name_ua', models.CharField(max_length=128, null=True, verbose_name='Название категории')),
                ('link', models.CharField(help_text='Используйте ссылку вида /#html_id для блока лэндинга. Остальные ссылки указывать полностью (https://...)', max_length=255, verbose_name='URL-адрес')),
                ('blog_items', models.ManyToManyField(to='communication.BlogItem', verbose_name='Статьи')),
            ],
            options={
                'verbose_name_plural': 'Категории в блоге',
                'verbose_name': 'Категория',
            },
        ),
    ]
