# Generated by Django 2.0.2 on 2018-03-14 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0026_auto_20180313_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeusemail',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='to_email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_email', to='communication.Email', verbose_name='Электронная почта для напишите нам'),
        ),
        migrations.DeleteModel(
            name='WriteUsEmail',
        ),
    ]
