# Generated by Django 2.0.2 on 2018-03-15 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0027_auto_20180314_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agreement',
        ),
    ]
