# Generated by Django 2.0.2 on 2018-03-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0029_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessFormStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок формы')),
                ('text', models.TextField(max_length=400, verbose_name='Текст формы')),
                ('extra_text', models.CharField(max_length=255, verbose_name='Дополнительный текст в левом нижнем углу')),
            ],
            options={
                'verbose_name': 'Форма успешной отправки сообщений',
                'verbose_name_plural': 'Формы успешной отправки сообщений',
            },
        ),
    ]
