# Generated by Django 2.0.2 on 2018-03-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0031_auto_20180319_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='success_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communication.SuccessFormStatic', verbose_name='Форма при успешной отправке сообщения'),
        ),
    ]
