# Generated by Django 2.0.2 on 2018-03-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0032_contact_success_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='successformstatic',
            options={'verbose_name': 'Форма успешно выполненного действия', 'verbose_name_plural': 'Формы успешно выполненного действия'},
        ),
    ]
