# Generated by Django 2.0.2 on 2018-03-26 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0033_auto_20180319_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExistMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='communication.SuccessFormStatic', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Форма, если пользователь уже зарегестрирован',
            },
        ),
    ]
