# Generated by Django 2.0.2 on 2018-03-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180326_0034'),
        ('communication', '0034_userexistmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата комментария')),
                ('content', models.TextField(max_length=1200, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Комментарии к вопросам пользователя',
                'verbose_name': 'Комментарий к вопросу пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Вопрос закрыт')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата вопроса')),
                ('content', models.TextField(max_length=1200, verbose_name='Вопрос')),
                ('comments', models.ManyToManyField(to='communication.QuestionComments', verbose_name='Комментарии')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Вопросы пользователей',
                'verbose_name': 'Вопрос пользователя',
            },
        ),
    ]
