# Generated by Django 2.0.2 on 2018-03-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0036_auto_20180327_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='comments',
            field=models.ManyToManyField(blank=True, to='communication.QuestionComment', verbose_name='Комментарии'),
        ),
    ]
