# Generated by Django 2.0.2 on 2018-03-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0038_questioncomment_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='От этого имени будут поститься комментарии к вопросам в ЛК')),
                ('message', models.TextField(max_length=1200, verbose_name='Сообщение, завершающее закрытые вопросы')),
            ],
            options={
                'verbose_name_plural': 'Конфигурация ответов в ЛК',
                'verbose_name': 'Конфигурация',
            },
        ),
    ]
