# Generated by Django 2.0.2 on 2018-03-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0039_questionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionconfig',
            name='message_ru',
            field=models.TextField(max_length=1200, null=True, verbose_name='Сообщение, завершающее закрытые вопросы'),
        ),
        migrations.AddField(
            model_name='questionconfig',
            name='message_ua',
            field=models.TextField(max_length=1200, null=True, verbose_name='Сообщение, завершающее закрытые вопросы'),
        ),
        migrations.AddField(
            model_name='questionconfig',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='От этого имени будут поститься комментарии к вопросам в ЛК'),
        ),
        migrations.AddField(
            model_name='questionconfig',
            name='name_ua',
            field=models.CharField(max_length=128, null=True, verbose_name='От этого имени будут поститься комментарии к вопросам в ЛК'),
        ),
    ]
