# Generated by Django 2.0.2 on 2018-03-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0040_auto_20180327_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='end_message',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='Завершающий ответ'),
        ),
    ]
