# Generated by Django 2.0.2 on 2018-03-27 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0041_userquestion_end_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='end_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='communication.QuestionComment', verbose_name='Завершающий ответ'),
        ),
    ]
