# Generated by Django 2.0.2 on 2018-03-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0042_auto_20180328_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncomment',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата вопроса'),
        ),
    ]
