# Generated by Django 2.0.2 on 2018-03-27 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0043_auto_20180328_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий к вопросу пользователя', 'verbose_name_plural': 'Комментарии к вопросам пользователя'},
        ),
        migrations.AlterModelOptions(
            name='userquestion',
            options={'ordering': ['updated_at'], 'verbose_name': 'Вопрос пользователя', 'verbose_name_plural': 'Вопросы пользователей'},
        ),
        migrations.RenameField(
            model_name='questioncomment',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='datetime',
        ),
        migrations.AddField(
            model_name='userquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания вопроса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления вопроса'),
        ),
    ]
