# Generated by Django 2.0.2 on 2018-03-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0047_auto_20180328_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='questions_files', verbose_name='Прикрепленный файл'),
        ),
    ]
