# Generated by Django 2.0.2 on 2018-03-29 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0048_userquestion_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackSuccessForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.SuccessFormStatic', verbose_name='Форма успешного заказа')),
            ],
            options={
                'verbose_name_plural': 'Форма после успешного заказа звонка',
                'verbose_name': 'Форма',
            },
        ),
    ]
