# Generated by Django 2.0.2 on 2018-03-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0049_callbacksuccessform'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитан'),
        ),
    ]
