# Generated by Django 2.0.2 on 2018-04-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0052_auto_20180330_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Пользователь'),
        ),
    ]
