# Generated by Django 2.0.2 on 2018-03-02 18:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название категории')),
            ],
            options={
                'verbose_name_plural': 'Категории вакансий',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название вакансии')),
                ('demands', ckeditor.fields.RichTextField(verbose_name='Требования')),
                ('conditions', ckeditor.fields.RichTextField(verbose_name='Условия')),
            ],
            options={
                'verbose_name_plural': 'Вакансии',
                'verbose_name': 'Вакансия',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='vacancies',
            field=models.ManyToManyField(to='vacancy.Vacancy', verbose_name='Вакансии'),
        ),
    ]
