# Generated by Django 2.0.2 on 2018-03-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Название вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name_ua',
            field=models.CharField(max_length=128, null=True, verbose_name='Название вакансии'),
        ),
    ]
