# Generated by Django 2.0.2 on 2018-03-12 21:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_auto_20180312_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='demands',
            field=ckeditor.fields.RichTextField(verbose_name='Требования'),
        ),
    ]
