# Generated by Django 2.0.2 on 2018-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_auto_20180312_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ua',
            field=models.CharField(max_length=128, null=True, verbose_name='Название категории'),
        ),
    ]
