# Generated by Django 2.0.2 on 2018-03-13 14:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_auto_20180313_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='conditions_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Условия [ru]'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions_ua',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Условия [ua]'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='demands_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Требования [ru]'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='demands_ua',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Требования [ua]'),
        ),
    ]
