# Generated by Django 2.0.2 on 2018-03-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_auto_20180313_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='conditions_ru',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='conditions_ua',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='demands_ru',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='demands_ua',
        ),
    ]
