# Generated by Django 2.0.2 on 2018-03-13 14:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0007_auto_20180313_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='conditions_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Условия'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions_ua',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Условия'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='demands_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Требования'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='demands_ua',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Требования'),
        ),
    ]
