# Generated by Django 2.0.2 on 2018-02-28 21:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spoiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=64, verbose_name='Тема спойлера')),
                ('content_left', ckeditor.fields.RichTextField(verbose_name='Текст левой колонки')),
                ('content_rigth', ckeditor.fields.RichTextField(verbose_name='Текст правой колонки')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Спойлер',
                'verbose_name_plural': 'Спойлеры',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('spoilers', models.ManyToManyField(to='content.Spoiler', verbose_name='Спойлеры')),
            ],
        ),
    ]
