# Generated by Django 2.0.2 on 2018-02-28 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180228_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'Статическая страница', 'verbose_name_plural': 'Статические страницы'},
        ),
        migrations.RenameField(
            model_name='spoiler',
            old_name='content_rigth',
            new_name='content_right',
        ),
    ]
