# Generated by Django 2.0.2 on 2018-03-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20180301_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='link',
            field=models.CharField(help_text='Используйте ссылки вида: url', max_length=255, verbose_name='URL-адрес'),
        ),
    ]
