# Generated by Django 2.0.2 on 2018-03-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_menufooteritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuFooterBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название блока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('items', models.ManyToManyField(to='content.MenuFooterItem', verbose_name='Пункты блока')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки меню в футере',
            },
        ),
    ]
