# Generated by Django 2.0.2 on 2018-03-02 17:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0009_email_active'),
        ('content', '0007_menufooterblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='job_page', verbose_name='Картинка')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Контактный телефон')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.Email', verbose_name='Контактная почта')),
            ],
            options={
                'verbose_name': 'Статический блок',
                'verbose_name_plural': 'Статическая часть страницы Вакансии',
            },
        ),
    ]
