# Generated by Django 2.0.2 on 2018-03-02 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_jobstaticpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstaticpage',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communication.PhoneNumber', verbose_name='Контактный телефон'),
        ),
    ]
