# Generated by Django 2.0.2 on 2018-03-03 09:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20180302_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки "Как получить кредит на главной"',
            },
        ),
    ]
