# Generated by Django 2.0.2 on 2018-03-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_getcredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getcredit',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
