# Generated by Django 2.0.2 on 2018-03-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20180303_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRateStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Небольшой текст')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Статический блок кредитные тарифы на главной',
            },
        ),
    ]
