# Generated by Django 2.0.2 on 2018-03-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_advantage_advantagestatic'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantagestatic',
            name='advantages',
            field=models.ManyToManyField(to='content.Advantage', verbose_name='Преимущества'),
        ),
    ]
