# Generated by Django 2.0.2 on 2018-03-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_advantagestatic_advantages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='image',
            field=models.FileField(upload_to='advantages', verbose_name='Иконка'),
        ),
    ]
