# Generated by Django 2.0.2 on 2018-03-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20180303_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='close_credit', verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='Текст')),
                ('link', models.CharField(help_text='Используйте ссылку вида /#html_id для блока лэндинга. Остальные ссылки указывать полностью (https://...)', max_length=255, verbose_name='URL-адрес')),
            ],
            options={
                'verbose_name_plural': 'Способы закрытия кредита',
                'verbose_name': 'Способ закрытия кредита',
            },
        ),
        migrations.CreateModel(
            name='CloseCreditStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('close_credits', models.ManyToManyField(to='content.CloseCredit', verbose_name='Варианты закрытия')),
            ],
            options={
                'verbose_name_plural': 'Блок закрытия кредита на главной',
                'verbose_name': 'Блок',
            },
        ),
    ]
