# Generated by Django 2.0.2 on 2018-03-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20180303_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Элементы безопасности на главной',
                'verbose_name': 'Элемент безопасности',
            },
        ),
        migrations.CreateModel(
            name='SecurityStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='secutiry_block', verbose_name='Картинка первого партнера')),
                ('image2', models.ImageField(upload_to='secutiry_block', verbose_name='Картинка второго партнера')),
                ('image3', models.ImageField(upload_to='secutiry_block', verbose_name='Картинка третьего партнера')),
                ('secutiry_items', models.ManyToManyField(to='content.SecurityItem', verbose_name='Элементы безопасности')),
            ],
            options={
                'verbose_name_plural': 'Блок о безопасности на главной',
                'verbose_name': 'Блок',
            },
        ),
    ]
