# Generated by Django 2.0.2 on 2018-03-05 14:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_securityitem_securitystatic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityitem',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
    ]
