# Generated by Django 2.0.2 on 2018-03-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20180305_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitystatic',
            name='image1',
            field=models.FileField(upload_to='secutiry_block', verbose_name='Картинка первого партнера'),
        ),
        migrations.AlterField(
            model_name='securitystatic',
            name='image2',
            field=models.FileField(upload_to='secutiry_block', verbose_name='Картинка второго партнера'),
        ),
        migrations.AlterField(
            model_name='securitystatic',
            name='image3',
            field=models.FileField(upload_to='secutiry_block', verbose_name='Картинка третьего партнера'),
        ),
    ]
