# Generated by Django 2.0.2 on 2018-03-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20180305_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitystatic',
            old_name='secutiry_items',
            new_name='security_items',
        ),
    ]
