# Generated by Django 2.0.2 on 2018-03-05 14:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20180305_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='discount', verbose_name='Картинка')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('link', models.CharField(help_text='Используйте ссылку вида /#html_id для блока лэндинга. Остальные ссылки указывать полностью (https://...)', max_length=255, verbose_name='URL-адрес')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блок скидка на главной',
            },
        ),
    ]
