# Generated by Django 2.0.2 on 2018-03-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_discountstatic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountstatic',
            name='image',
            field=models.FileField(upload_to='discount', verbose_name='Картинка'),
        ),
    ]
