# Generated by Django 2.0.2 on 2018-03-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20180305_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountstatic',
            name='image',
        ),
    ]
