# Generated by Django 2.0.2 on 2018-03-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_remove_discountstatic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountstatic',
            name='image',
            field=models.FileField(default=1, upload_to='discount', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
