# Generated by Django 2.0.2 on 2018-03-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_socialnet'),
        ('content', '0025_discountstatic_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=64, verbose_name='Подзаголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('link', models.CharField(help_text='Используйте ссылку вида /#html_id для блока лэндинга. Остальные ссылки указывать полностью (https://...)', max_length=255, verbose_name='URL-адрес')),
                ('image', models.ImageField(upload_to='about_us', verbose_name='Картинка')),
                ('middle_title', models.CharField(max_length=128, verbose_name='Заголовок на середине страницы')),
                ('middle_text', models.TextField(verbose_name='Текст на середине страницы')),
                ('important_title', models.CharField(max_length=128, verbose_name='Заголовок важных аспектов')),
                ('advantages', models.ManyToManyField(to='content.Advantage', verbose_name='Преимущества')),
            ],
            options={
                'verbose_name': 'Страница о нас',
                'verbose_name_plural': 'Страница о нас',
            },
        ),
        migrations.CreateModel(
            name='ImportantAspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='important_aspect', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Аспект',
                'verbose_name_plural': 'Важные аспекты',
            },
        ),
        migrations.AddField(
            model_name='aboutusstatic',
            name='important_aspects',
            field=models.ManyToManyField(to='content.ImportantAspect', verbose_name='Важные аспекты'),
        ),
        migrations.AddField(
            model_name='aboutusstatic',
            name='responses',
            field=models.ManyToManyField(to='communication.Response', verbose_name='Отзывы'),
        ),
    ]
