# Generated by Django 2.0.2 on 2018-03-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_auto_20180305_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantaspect',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='important_aspect', verbose_name='Картинка'),
        ),
    ]
