# Generated by Django 2.0.2 on 2018-03-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20180305_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closecredit',
            name='image',
        ),
        migrations.AddField(
            model_name='closecredit',
            name='icon_class',
            field=models.CharField(choices=[('Терминал', 'svg-phone'), ('Личный кабинет', 'svg-tablet'), ('Банк', 'svg-house')], default=1, max_length=128, verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
