# Generated by Django 2.0.2 on 2018-03-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_auto_20180306_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountstatic',
            name='image',
            field=models.ImageField(upload_to='discount', verbose_name='Картинка заднего фона'),
        ),
    ]
