# Generated by Django 2.0.2 on 2018-03-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_auto_20180306_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagetopblockstatic',
            name='footer',
            field=models.CharField(default=1, max_length=128, verbose_name='Подзаголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainpagetopblockstatic',
            name='subtitle',
            field=models.CharField(max_length=128, verbose_name='Вторая строка заголовка'),
        ),
        migrations.AlterField(
            model_name='mainpagetopblockstatic',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Первая строка заголовка'),
        ),
    ]
