# Generated by Django 2.0.2 on 2018-03-06 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_creditrateup'),
        ('communication', '0013_remove_socialnet_image'),
        ('department', '0004_remove_department_city'),
        ('content', '0034_auto_20180306_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.AdvantageStatic', verbose_name='Блок преимущества')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.AddField(
            model_name='creditratestatic',
            name='credit_rates',
            field=models.ManyToManyField(to='credit.CreditRate', verbose_name='Кредитные тарифы'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='credit_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.CreditRateStatic', verbose_name='Блок кредитные тарифы'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='credit_close',
            field=models.ManyToManyField(to='content.CloseCreditStatic', verbose_name='Блок как закрыть кредит'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='credit_take',
            field=models.ManyToManyField(to='content.GetCredit', verbose_name='Блок как получить кредит'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='credits_up',
            field=models.ManyToManyField(to='credit.CreditRateUp', verbose_name='Кредитные тарифы вверху страницы'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='departments',
            field=models.ManyToManyField(to='department.Department', verbose_name='Отделы'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.DiscountStatic', verbose_name='Блок акция'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='menu_footer',
            field=models.ManyToManyField(to='content.MenuFooterBlock', verbose_name='Меню в футере'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='responses',
            field=models.ManyToManyField(to='communication.Response', verbose_name='Блок отзывы'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='security',
            field=models.ManyToManyField(to='content.SecurityStatic', verbose_name='Блок о параметрах защиты'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='social_nets',
            field=models.ManyToManyField(to='communication.SocialNet', verbose_name='Социальные сети в футере'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='top_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.MainPageTopBlockStatic', verbose_name='Верхний блок страницы'),
        ),
    ]
