# Generated by Django 2.0.2 on 2018-03-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_auto_20180306_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditratestatic',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блок кредитные тарифы на главной'},
        ),
    ]
