# Generated by Django 2.0.2 on 2018-03-07 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_remove_department_city'),
        ('communication', '0013_remove_socialnet_image'),
        ('content', '0037_auto_20180306_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.AdvantageStatic', verbose_name='Блок преимущества')),
                ('credit_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.CreditRateStatic', verbose_name='Блок кредитные тарифы')),
                ('credit_close', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.CloseCreditStatic', verbose_name='Блок как закрыть кредит')),
                ('credit_take', models.ManyToManyField(to='content.GetCredit', verbose_name='Блок как получить кредит')),
                ('departments', models.ManyToManyField(to='department.Department', verbose_name='Отделения')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.DiscountStatic', verbose_name='Блок акция')),
                ('menu_footer', models.ManyToManyField(to='content.MenuFooterBlock', verbose_name='Меню в футере')),
                ('responses', models.ManyToManyField(to='communication.Response', verbose_name='Блок отзывы')),
                ('security', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.SecurityStatic', verbose_name='Блок о параметрах защиты')),
                ('social_nets', models.ManyToManyField(to='communication.SocialNet', verbose_name='Социальные сети в футере')),
            ],
            options={
                'verbose_name': 'Страница Партнерский лэндинг',
                'verbose_name_plural': 'Страница Партнерский лэндинг',
            },
        ),
    ]
