# Generated by Django 2.0.2 on 2018-03-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_indexpagestatic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpagestatic',
            name='menu_footer',
        ),
        migrations.RemoveField(
            model_name='indexpagestatic',
            name='social_nets',
        ),
    ]
