# Generated by Django 2.0.2 on 2018-03-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_auto_20180307_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantaspect',
            name='image',
            field=models.FileField(null=True, upload_to='important_aspect', verbose_name='Картинка'),
        ),
    ]
