# Generated by Django 2.0.2 on 2018-03-08 21:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_auto_20180307_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Информация по кредитам',
                'verbose_name_plural': 'Информация по кредитам',
            },
        ),
        migrations.CreateModel(
            name='CreditInformationBlockStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('information_items', models.ManyToManyField(to='content.CreditInformation', verbose_name='Блоки информации')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Информация о кредитах на главной над футером',
            },
        ),
        migrations.AddField(
            model_name='indexpagestatic',
            name='credit_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.CreditInformationBlockStatic', verbose_name='Блок информации о кредитах'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='credit_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.CreditInformationBlockStatic', verbose_name='Блок информации о кредитах'),
        ),
    ]
