# Generated by Django 2.0.2 on 2018-03-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_auto_20180308_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditinformationblockstatic',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блок информации по кредитах на главной над футером'},
        ),
    ]
