# Generated by Django 2.0.2 on 2018-03-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_auto_20180308_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpagestatic',
            name='credit_information',
        ),
    ]
