# Generated by Django 2.0.2 on 2018-03-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_remove_indexpagestatic_credit_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuHeaderBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Блок меню в хедере',
                'verbose_name': 'Блок',
            },
        ),
        migrations.CreateModel(
            name='MenuHeaderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название пункта')),
                ('link', models.CharField(help_text='Используйте ссылку вида /#html_id для блока лэндинга. Остальные ссылки указывать полностью (https://...)', max_length=255, verbose_name='URL-адрес')),
            ],
            options={
                'verbose_name_plural': 'Пункты меню в хедере',
                'verbose_name': 'Пункт меню',
            },
        ),
        migrations.AddField(
            model_name='menuheaderblock',
            name='items',
            field=models.ManyToManyField(to='content.MenuHeaderItem', verbose_name='Пункты'),
        ),
    ]
