# Generated by Django 2.0.2 on 2018-03-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_auto_20180309_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuheaderitem',
            options={'ordering': ['order'], 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню в хедере'},
        ),
        migrations.AddField(
            model_name='menuheaderitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='menufooteritem',
            name='link',
            field=models.CharField(help_text='Используйте ссылку вида html_id для блока лэндинга. Остальные ссылки указывать полностью (https://...)', max_length=255, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='menuheaderitem',
            name='link',
            field=models.CharField(help_text='Используйте ссылку вида html_id для блока лэндинга. Остальные ссылки указывать полностью (https://...)', max_length=255, verbose_name='URL-адрес'),
        ),
    ]
