# Generated by Django 2.0.2 on 2018-03-12 15:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_auto_20180309_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagestatic',
            name='h1',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='meta_description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Meta description страницы'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='meta_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Meta title страницы'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Title страницы'),
        ),
    ]
