# Generated by Django 2.0.2 on 2018-03-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_auto_20180312_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpagestatic',
            name='h1',
        ),
    ]
