# Generated by Django 2.0.2 on 2018-03-13 12:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_auto_20180312_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='closecreditstatic',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок [ru]'),
        ),
        migrations.AddField(
            model_name='closecreditstatic',
            name='title_ua',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок [ua]'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='meta_description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Meta description страницы [ru]'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='meta_description_ua',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Meta description страницы [ua]'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='meta_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Meta title страницы [ru]'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='meta_title_ua',
            field=models.CharField(max_length=255, null=True, verbose_name='Meta title страницы [ua]'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title страницы [ru]'),
        ),
        migrations.AddField(
            model_name='mainpagestatic',
            name='title_ua',
            field=models.CharField(max_length=255, null=True, verbose_name='Title страницы [ua]'),
        ),
    ]
