# Generated by Django 2.0.2 on 2018-03-14 14:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0054_auto_20180313_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagestatic',
            name='copyright',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Копирайт в футере'),
        ),
        migrations.AlterField(
            model_name='spoiler',
            name='content_left',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст левой колонки'),
        ),
        migrations.AlterField(
            model_name='spoiler',
            name='content_left_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст левой колонки'),
        ),
        migrations.AlterField(
            model_name='spoiler',
            name='content_left_ua',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст левой колонки'),
        ),
        migrations.AlterField(
            model_name='spoiler',
            name='content_right',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст правой колонки'),
        ),
        migrations.AlterField(
            model_name='spoiler',
            name='content_right_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст правой колонки'),
        ),
        migrations.AlterField(
            model_name='spoiler',
            name='content_right_ua',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст правой колонки'),
        ),
    ]
