# Generated by Django 2.0.2 on 2018-03-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0057_auto_20180315_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagestatic',
            name='departments_title',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок над отделениями'),
        ),
        migrations.AddField(
            model_name='indexpagestatic',
            name='departments_title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок над отделениями [ru]'),
        ),
        migrations.AddField(
            model_name='indexpagestatic',
            name='departments_title_ua',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок над отделениями [ua]'),
        ),
    ]
