# Generated by Django 2.0.2 on 2018-03-15 22:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0058_auto_20180315_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPageDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=128, null=True, verbose_name='Заголовок')),
                ('title_ua', models.CharField(max_length=128, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='static_page_default', verbose_name='Картинка')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('text_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Текст')),
                ('text_ua', ckeditor.fields.RichTextField(null=True, verbose_name='Текст')),
                ('link', models.CharField(help_text='Используйте ссылки вида: url', max_length=255, verbose_name='URL-адрес')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
            },
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'Статическая страница', 'verbose_name_plural': 'Статические страницы со спойлерами'},
        ),
    ]
