# Generated by Django 2.0.2 on 2018-03-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0059_auto_20180316_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='link',
            field=models.CharField(help_text='Используйте ссылки вида: /url', max_length=255, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='staticpagedefault',
            name='link',
            field=models.CharField(help_text='Используйте ссылки вида: /url', max_length=255, verbose_name='URL-адрес'),
        ),
    ]
