# Generated by Django 2.0.2 on 2018-03-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0061_auto_20180316_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuaboutitem',
            name='link',
            field=models.CharField(help_text='Используйте ссылку вида #html_id для блока лэндинга. Остальные ссылки указывать полностью (https://...)', max_length=255, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='menufooteritem',
            name='link',
            field=models.CharField(help_text='Используйте ссылку вида #html_id для блока лэндинга. Остальные ссылки указывать полностью (https://...)', max_length=255, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='menuheaderitem',
            name='link',
            field=models.CharField(help_text='Используйте ссылку вида #html_id для блока лэндинга. Остальные ссылки указывать полностью (https://...)', max_length=255, verbose_name='URL-адрес'),
        ),
    ]
