# Generated by Django 2.0.2 on 2018-03-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0065_auto_20180327_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountstatic',
            name='icon',
            field=models.FileField(null=True, upload_to='discount_icons', verbose_name='Иконки'),
        ),
        migrations.AlterField(
            model_name='discountstatic',
            name='image',
            field=models.ImageField(null=True, upload_to='discount', verbose_name='Картинка заднего фона'),
        ),
    ]
