# Generated by Django 2.0.2 on 2018-04-04 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_creditrate_is_insurance'),
        ('content', '0066_auto_20180327_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagestatic',
            name='credit_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.CreditRate', verbose_name='Кредитный тариф калькулятора'),
        ),
    ]
