# Generated by Django 2.0.2 on 2018-04-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0067_indexpagestatic_credit_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityitem',
            name='icon_class',
            field=models.CharField(choices=[('handshake', 'Рукопожатие'), ('shield', 'Щит'), ('wax', 'Достижение')], default=1, max_length=128, verbose_name='Иконка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitystatic',
            name='image4',
            field=models.FileField(default=1, upload_to='secutiry_block', verbose_name='Картинка четвертого партнера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitystatic',
            name='image5',
            field=models.FileField(default=1, upload_to='secutiry_block', verbose_name='Картинка пятого партнера'),
            preserve_default=False,
        ),
    ]
