# Generated by Django 2.0.2 on 2018-02-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('schedule', models.CharField(max_length=128, verbose_name='Режим работы')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.CharField(max_length=64, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
    ]
