# Generated by Django 2.0.2 on 2018-03-01 18:23

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20180228_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=128, verbose_name='Адрес'),
        ),
    ]
