# Generated by Django 2.0.2 on 2018-03-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20180301_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='city',
        ),
    ]
