# Generated by Django 2.0.2 on 2018-03-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_auto_20180312_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='department',
            name='address_ua',
        ),
    ]
