# Generated by Django 2.0.2 on 2018-03-12 21:19

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_auto_20180312_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='address_ru',
            field=django_google_maps.fields.AddressField(max_length=128, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='department',
            name='address_ua',
            field=django_google_maps.fields.AddressField(max_length=128, null=True, verbose_name='Адрес'),
        ),
    ]
