# Generated by Django 2.0.2 on 2018-03-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_auto_20180312_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='department',
            name='address_ua',
        ),
    ]
