# Generated by Django 2.0.2 on 2018-03-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_auto_20180313_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='address_ua',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес [ua]'),
        ),
    ]
