# Generated by Django 2.0.2 on 2018-03-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(blank=True, max_length=12, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('credit_sum', models.IntegerField(blank=True, null=True, verbose_name='Сумма кредита')),
                ('termin', models.CharField(default='2', max_length=32, verbose_name='Срок кредита (к-ство недель/месяцев)')),
                ('termin_type', models.CharField(default='неделя', max_length=32, verbose_name='Тип срока (неделя/месяц)')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
