# Generated by Django 2.0.2 on 2018-03-03 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название тарифа')),
                ('image', models.ImageField(upload_to='credit_rate', verbose_name='Картинка')),
                ('sum_min', models.PositiveIntegerField(verbose_name='Минимальная сумма кредита')),
                ('sum_max', models.PositiveIntegerField(verbose_name='Максимальная сумма кредита')),
                ('term_min', models.PositiveIntegerField(verbose_name='Минимальный срок кредита')),
                ('term_max', models.PositiveIntegerField(verbose_name='Максимальный срок кредита')),
                ('rate_min', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Минимальная ставка, %')),
                ('rate_max', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Максимальная ставка, %')),
            ],
            options={
                'verbose_name': 'Кредитный тариф',
                'verbose_name_plural': 'Кредитные тарифы',
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Пр. раз в месяц', max_length=128, verbose_name='Платеж')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Сроки платежей',
            },
        ),
        migrations.AddField(
            model_name='creditrate',
            name='payment_terms',
            field=models.ManyToManyField(to='credit.PaymentTerm', verbose_name='Сроки платежей'),
        ),
    ]
