# Generated by Django 2.0.2 on 2018-03-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrate',
            name='term_max',
            field=models.PositiveIntegerField(verbose_name='Максимальный срок кредита, недель'),
        ),
        migrations.AlterField(
            model_name='creditrate',
            name='term_min',
            field=models.PositiveIntegerField(verbose_name='Минимальный срок кредита, недель'),
        ),
    ]
