# Generated by Django 2.0.2 on 2018-03-06 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20180303_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRateUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(choices=[('cash', 'Наличка'), ('stick-man', 'Пенсионер'), ('sticker', 'Стикер')], max_length=128, verbose_name='Иконка')),
                ('credit_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.CreditRate', verbose_name='Кредитный тариф')),
            ],
            options={
                'verbose_name_plural': 'Популярные кредитные тарифы, вверху на главной',
                'verbose_name': 'Популярный кредитный тариф',
            },
        ),
    ]
