# Generated by Django 2.0.2 on 2018-03-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_creditrateup'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrate',
            name='rate_file',
            field=models.FileField(default=1, upload_to='rates_files', verbose_name='Файл с процентами, формат .json'),
            preserve_default=False,
        ),
    ]
