# Generated by Django 2.0.2 on 2018-03-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_creditrate_rate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrate',
            name='term_type',
            field=models.BooleanField(default=False, help_text='Если включено, то в месяцах Если отключено, то в неделях', verbose_name='Тип срока кредита'),
        ),
        migrations.AlterField(
            model_name='creditrate',
            name='term_max',
            field=models.PositiveIntegerField(verbose_name='Максимальный срок кредита'),
        ),
        migrations.AlterField(
            model_name='creditrate',
            name='term_min',
            field=models.PositiveIntegerField(verbose_name='Минимальный срок кредита'),
        ),
    ]
