# Generated by Django 2.0.2 on 2018-03-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_auto_20180309_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrate',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Название тарифа'),
        ),
        migrations.AddField(
            model_name='creditrate',
            name='name_ua',
            field=models.CharField(max_length=128, null=True, verbose_name='Название тарифа'),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='term_ru',
            field=models.CharField(help_text='Пр. раз в месяц', max_length=128, null=True, verbose_name='Платеж'),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='term_ua',
            field=models.CharField(help_text='Пр. раз в месяц', max_length=128, null=True, verbose_name='Платеж'),
        ),
    ]
