# Generated by Django 2.0.2 on 2018-03-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_auto_20180312_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrate',
            name='is_insurance',
            field=models.BooleanField(default=False, verbose_name='Страховка'),
        ),
    ]
